pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
		sh """
                    echo ${PATH}
		    make install
		    make lint
                """
                echo "env ${env.BUILD_ID} on ${env.JENKINS_URL}"
		echo "env ${env.BUILD_NUMBER} on ${env.JOB_NAME}"
		echo "env ${env.EXECUTOR_NUMBER} on ${env.BUILD_TAG}"
		echo "env ${env.WORKSPACE} on ${env.NODE_NAME}"
            }
        }
    }
}
