pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
		sh """
                    export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/var/lib/jenkins/.local/bin:$PATH"
                    echo ${PATH}
		    make install
		    make lint
                    make hadolint
                    echo "building with docker"
                    docker build --tag=manuelecdev/udafinalproject-${env.BUILD_TAG} .
                    echo "docker image ls"
                    docker image ls
                    echo "Docker ID and Image: manuelecdev/udafinalproject-${env.BUILD_TAG}"
                    cat /password | docker login --username manuelecdev --password-stdin
                    echo "docker image push"
                    docker image push manuelecdev/udafinalproject-${env.BUILD_TAG}
                """
            }
        }

        stage('Deploy') {
            steps {
                sh """
                    export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/var/lib/jenkins/.local/bin:$PATH"
                    echo ${PATH}
                    echo "deploy kube cluster"
                    ansible-playbook ./.jenkins/ansible/main.yml -i /etc/ansible/inventory
                    ansible-playbook ./.jenkins/ansible/main-deploy-app.yml -i /etc/ansible/inventory
                """
            }
        }
    }
}
